package:
  name: calour
  version: !!str master

source:
  git_url: git@github.com:biocore/calour.git


requirements:
  build:
    - python
    - nose
    - setuptools
    - numpy
    - scipy
    - pandas
    - matplotlib >=2.0
    - scikit-learn
    - scikit-bio >=0.5.1
    - biom-format
    - statsmodels
    - ipython
    - ipywidgets
    - pyqt >5
    - docrep
  run:
    - python
    - nose
    - setuptools
    - numpy
    - scipy
    - pandas
    - matplotlib >=2.0
    - scikit-learn
    - scikit-bio >=0.5.1
    - biom-format
    - statsmodels
    - ipython
    - ipywidgets
    - pyqt >5
    - docrep
test:
  # Python imports
  imports:
    - calour
    - calour.experiment

about:
  home: https://github.com/biocore/calour
  license: Modified BSD License
  summary: exploratory and interactive microbiome analyses based on heatmaps

